# main text of home
name: Dongjo Ban
bio: Welcome to my page!

# twitter summary info
# description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: true
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: assets/resume/resume.pdf

url: https://dongjoban17.github.io
# your url: http://USERNAME.github.io

permalink: /:title/

# if you don't want comments in your posts, leave categories empty
# disqus:
#   shortname: mydisqus # enter this from your disqus account
#   categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: dongjoban
# youtube: myyoutube
# spotify: myspotify
# github: mygithub
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: dongjoban17@gmail.com

authors:
    dongjo:
        name: Dongjo Ban
        bio: An aspiring bioinformatician
        external-image: true
        picture: assets/images/profile.jpg

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

#projects: true
about: true
blog: true

# show the "read time" of the posts?
read-time: false

# show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: false

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
